project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
  elsevier-pdf:
    # keep-tex: true
    journal:
      name: Forest Policy and Economics
      formatting: review
      model: 3p
      cite-style: authoryear
    include-in-header: 
      text: |
        \newpageafter{author}