from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
include: 'rules/correspondence_FAO_HS.smk'
include: 'rules/get_uncomtrade.smk'
include: 'rules/wb_data.smk'
include: 'rules/deflate_uncomtrade.smk'
include: 'rules/plot_outliers.smk'
include: 'rules/merge_data.smk'
include: 'rules/format_data_network_analysis.smk'
include: 'rules/network_objects.smk'
include: 'rules/contributor_profiles.smk'
include: 'rules/market_concentration.smk'
include: 'rules/network_composition.smk'
include: 'rules/network_connectivity.smk'
include: 'rules/network_contribution.smk'
include: 'rules/plot_network_composition.smk'
include: 'rules/plot_market_concentration.smk'
include: 'rules/plot_contributor_profiles.smk'
include: 'rules/plot_network_connectivity.smk'

# target rule
rule all:
    input:
        # expand('results/processed_data/network_analysis/plot/{fao_div}/network_connectivity.{ext}',
        #        fao_div = config['fao_divisions'],
        #        ext = ['png', 'svg']),
        # expand('results/processed_data/network_analysis/plot/{fao_div}/contributor_profiles/profiles_{year}.{ext}',
        #        fao_div = config['fao_divisions'],
        #        year = list(range(config['years']['start'], 
        #                          config['years']['stop']-1)),
        #        ext = ['png', 'svg']),
        # expand('results/processed_data/network_analysis/plot/{fao_div}/market_concentration.{ext}',
        #             fao_div = config['fao_divisions'],
        #             ext = ['png', 'svg']),
        # expand('results/processed_data/network_analysis/plot/{fao_div}/network_composition.{ext}',
        #        fao_div = config['fao_divisions'],
        #        ext = ['png', 'svg']),
        # 'results/processed_data/network_analysis/output/network_metrics.csv',
        # 'results/processed_data/network_analysis/output/network_contribution.csv',
        # 'results/processed_data/network_analysis/output/network_connectivity.csv',
        # 'results/processed_data/network_analysis/output/network_composition.csv',
        # 'results/processed_data/network_analysis/output/market_concentration.csv',
        # 'results/processed_data/network_analysis/output/contributor_profiles.csv',
        # 'results/processed_data/network_analysis/intermediary/edge_lists.pkl',
        # 'results/processed_data/network_analysis/intermediary/mirror_flows.csv',
        # 'results/processed_data/network_analysis/input/input_data.parquet.gzip',
        'results/processed_data/global/merged_data.parquet.gzip',
        # 'results/processed_data/global/deflate_uncomtrade_data.parquet.gzip',
        # 'resources/raw_data/public/uncomtrade_data.parquet.gzip',
        # 'resources/raw_data/public/wb_series_data.csv',
        # 'resources/raw_data/public/wb_countries_data.csv',
        # 'resources/raw_data/inhouse/correspondence_FAO_HS.json'
