from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
include: 'rules/correspondence_FAO_HS.smk'
include: 'rules/get_uncomtrade.smk'
include: 'rules/wb_data.smk'
include: 'rules/deflate_uncomtrade.smk'
include: 'rules/join_fao_code.smk'
include: 'rules/aggregate_eu.smk'
include: 'rules/filter_data.smk'
include: 'rules/network_objects.smk'
include: 'rules/contributor_profiles.smk'
include: 'rules/market_concentration.smk'
include: 'rules/network_composition.smk'
include: 'rules/network_connectivity.smk'
include: 'rules/network_contribution.smk'
include: 'rules/plot_network_composition.smk'
include: 'rules/plot_prices_figures.smk'
include: 'rules/plot_market_concentration.smk'
include: 'rules/plot_contributor_profiles.smk'
include: 'rules/plot_network_connectivity.smk'
include: 'rules/plot_network_contribution.smk'
include: 'rules/plot_trade_flows.smk'

# target rule
rule all:
    input:
        expand('results/network_analysis/plot/{fao_div}/{wgt}/network_contribution.{ext}',
               fao_div  = config['fao_divisions_agg'],
               wgt      = config['weight'],
               ext      = ['png', 'svg']),
        expand('results/network_analysis/agg_eu/plot/01/contributor_profiles.{ext}',
               ext = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/market_concentration.{ext}',
                agg_lvl  = config['agg_lvl'],
                fao_div  = config['fao_divisions_agg'],
                ext      = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/network_connectivity.{ext}',
                        agg_lvl = config['agg_lvl'],
                        fao_div = config['fao_divisions_agg'],
                        ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/network_mirrored_desc_stat_{metric}.{ext}',
                agg_lvl = config['agg_lvl'],
                fao_div = config['fao_divisions_agg'],
                metric  = ['value', 'weight'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/network_composition.{ext}',
                agg_lvl = config['agg_lvl'],
                fao_div = config['fao_divisions_agg'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/network_price_desc_stat.{ext}',
                agg_lvl = config['agg_lvl'],
                fao_div = config['fao_divisions_agg'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/country_lvl/plot/01/network_price_{fig}.{ext}',
                fig     = ['partners',
                           'ridgeline_countries_imp',
                           'ridgeline_countries_exp',
                           'ridgeline_years_imp',
                           'ridgeline_years_exp'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/chord_diagram.{ext}',
                agg_lvl = config['agg_lvl'],
                fao_div = config['fao_divisions_agg'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/plot/{fao_div}/trade_network.{ext}',
                agg_lvl = config['agg_lvl'],
                fao_div = config['fao_divisions_agg'],
                ext     = ['png', 'svg']),
        expand('results/network_analysis/{agg_lvl}/output/contributor_profiles.csv',
                agg_lvl = config['agg_lvl']),
        expand('results/network_analysis/{agg_lvl}/output/network_connectivity.csv',
                agg_lvl  = config['agg_lvl']),
        expand('results/network_analysis/{agg_lvl}/output/market_concentration.csv',
                agg_lvl  = config['agg_lvl']),
        expand('results/network_analysis/{agg_lvl}/output/network_contribution.csv',
                agg_lvl  = config['agg_lvl']),
        expand('results/network_analysis/{agg_lvl}/output/network_composition.csv',
                agg_lvl  = config['agg_lvl']),
        # expand('results/network_analysis/{agg_lvl}/intermediary/mirror_flows.csv',
        #         agg_lvl  = config['agg_lvl']),
        # expand('results/network_analysis/{agg_lvl}/intermediary/edge_lists.pkl',
        #         agg_lvl  = config['agg_lvl']),
        # 'results/network_analysis/agg_eu/input/input_data.parquet.gzip',
        # 'results/network_analysis/country_lvl/input/input_data.parquet.gzip',
        # 'results/global/merged_data.csv',
        # 'results/global/deflate_uncomtrade_data.parquet.gzip',
        # 'resources/public/uncomtrade_data.parquet.gzip',
        # 'resources/public/wb_series_data.csv',
        # 'resources/inhouse/correspondence_FAO_HS.json'
