# Years of trade
years:
  start: 1996
  stop: 2024  # process will consider stop year - 1 only

# HS code version --> different classifications according to the year
HS_version: [1996, 2002, 2007, 2012, 2017, 2022]

# Trade flows to download --> Imports, Exports
flowCode: ['M', 'X']

# Product to keep (FAO classification)
fao_divisions: ['012']
# This keeps trade flows of roundwood products (FAO classification of forest
# products 2022):
# - Wood in the rough, other than wood fuel (Division code: 012)

# World Bank series --> data of interest from World Bank
wb_series:
  [
    # Unit value index for convertion into constant USD 2015
    'TM.UVI.MRCH.XD.WD', # Import unit value index (2015 = 100)
    'TX.UVI.MRCH.XD.WD', # Export unit value index (2015 = 100)
  ]

# ISO code to exclude from analysis
excluded_iso: ['XX', '_X', '\d']
# This excludes the following non-country reporters or partners:
#    ['Southern African Customs Union (...1999)', 'Other Asia, nes',
#    'World', 'Areas, nes', 'Oceania, nes', 'Bunkers',
#    'Special Categories', 'Other Europe, nes', 'Other Africa, nes',
#    'Rest of America, nes', 'Free Zones', 'Western Asia, nes',
#    'CACM, nes', 'LAIA, nes', 'Caribbean, nes', 'Northern Africa, nes',
#    'North America and Central America, nes']

# Columns to keep for analysis (lighten computation)
col_keep: ['period', 
           'reporterISO', 
           'reporterDesc', 
           'flowCode', 
           'partnerISO', 
           'partnerDesc',
           'FAO Code',
           'FAO Product',  
           'netWgt', 
           'primaryValue', 
           'primaryValue_deflated']

# The weight of network edges to choose
weight: 'primary_value'

# Threshold to apply for identifying main contributors to trade
threshold_main_contributors: 0.01


